encoding: utf-8
markdown: redcarpet
baseurl: /jekyll-course-template
url: p2pu.github.io/jekyll-course-template/
permalink: /:title/
ga_tracking_code: UA-5757664-17
disqus_shortname: jekyllcoursetemplate
prose:
  media: /img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
